---
downloads: ~/.ansible-downloads/

configure_dot_files: yes

dotfiles_repo: https://github.com/seankay/.dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_version: master
dotfiles_repo_local_destination: ~/.dotfiles

homebrew_installed_packages:
  - antigen
  - awscli
  - bash-completion
  - fzf
  - go
  - gnupg
  - jq
  - neovim
  - node
  - python
  - python@2
  - rbenv
  - terraform
  - the_silver_searcher
  - { name: universal-ctags/universal-ctags/universal-ctags, install_options: "HEAD" }
  - tmux
  - trash-cli
  - gh
  - saw
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - TylerBrock/saw

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - aws-vault
  - docker
  - google-backup-and-sync
  - google-chrome
  - slack
  - 1password
  - sublime-text
  - spotify
  - alfred
  - caffeine
  - postman
  - spectacle
  - iterm2
  - istat-menus
  - tableplus
  - table-tool
  - transmit
  - typora
  - 1password-cli

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
  - name: yapf
  - name: flake8
  - name: tmuxp
  - name: neovim

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
